services:
  mongodb:
    image: mongo:latest
    container_name: inventory-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "6333:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=inventory-demo
    healthcheck:
      test: mongosh --eval "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:hostname()+':27017'}]}) }"
      interval: 5s
      timeout: 30s
      retries: 5
